export const PHRASES = [
  "Someone mute please",
  "Echo hell",
  "Dog barking",
  "Phone dropped",
  "Lost video",
  "Are you on mute?",
  "I’ll just email you",
  "Kid screaming",
  "Vacuum sounds",
  "“Honey, I’m in a meeting!”",
  "Chewing sounds",
  "Bathroom noises",
  "Rustling to put on headset",
  "Excessive Typing",
  "“Is someone talking? I can’t hear”",
  "Robot voice",
  "“Can you all see my screen?”",
  "Screen displays something NSFW",
  "Dial in to someone’s voicemail",
  "Awkward talking over each other",
  "Sorry I’m late, I “lost track of time”",
  "I’ll give you all your time back",
  "Someone walking while talking",
  "Small talk takes up over half the meeting",
];

export const GAME_SIZE = 5;
